server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: aA111111
    # druid配置
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat,wall,config
      # 初始化数量
      initial-size: 1
      # 最大链接数
      max-active: 100
      # 获取链接的等待超时时间
      max-wait: 60000
      # 最小连接数
      min-idle: 1
      # 间隔多久需要进行一次检测，检测的目的是关闭空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 测试sql
      validation-query: select 'x'
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 20
      # druid的可视化界面的参数配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
        deny: 192.168.10.1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huawei.l00379880.admin.model
  configuration:
    map-underscore-to-camel-case: true